module.exports = {
  SYSTEM: "SYSTEM",
  LIKE: "LIKE",
  COMMENT_REPLY: "COMMENT_REPLY",
  STAR: "STAR",
  TOPIC_LIKE: "TOPIC_LIKE",
  TOPIC_COMMENT_REPLY: "TOPIC_COMMENT_REPLY",
  TOPIC_STAR: "TOPIC_STAR",
};
