const DEFAULT_PLACHOLDER = "请在此输入评论";
const DEFAULT_COMMENT = "";
const SUBSCRIBE_REMIND_TEMPID = "Ow0YwQqaWJdxdJGO6kSDA_9Ac_v21AREySFvzv4bRuc"

module.exports = {
    DEFAULT_PLACHOLDER,
    DEFAULT_COMMENT,
    SUBSCRIBE_REMIND_TEMPID
}